version: '3.9'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      # CONNECTION_STRING: mongodb://teste123:e296cd9f@localhost:27017/admin?authSource=admin
      # STOCK_COLLECTION: STOCKS
      # FIAT_COLLECTION: FIATS
      # DATABASE: CUSTOM_COMMAND
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      # RABBITMQ_HOST: localhost:5672/
      RABBITMQ_HOST: localhost
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: teste
      RABBITMQ_QUEUE: event-queue
      RABBITMQ_EXCHANGE: event-exchange
      RABBITMQ_DLQ_EXCHANGE: event-exchange-dlq
      RABBITMQ_DLQ_QUEUE: event-queue-dlq
      RABBITMQ_ERROR_QUEUE: event-error-queue
      RABBITMQ_TTL: 5000
      RABBITMQ_MAX_RETRY: 3
      RABBITMQ_PREFETCH_COUNT: 10
      RABBITMQ_ROUTING_KEY: event-routing
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: teste123
      MONGO_INITDB_ROOT_PASSWORD: e296cd9f
    networks:
      - mongo-compose-network
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
networks: 
    mongo-compose-network:
      driver: bridge



